name: Container 
on:
  workflow_dispatch:
    
jobs:
  node-docker:
    runs-on: ubuntu-latest 
    container:
      image: node:14.21.0-alpine3.16
    steps:
      - name: Log node version 
        run: |
          node -v 
          cat /etc/os-release 